---
#Плагин до модифицырывал opkiler22789 если будут сбои пишем --> http://vk.com/olekseyua
#Сколько стоит Дешевое казино, "$" не ставим
cheap: 150
#Сколько стоит Дорогое казино, "$" не ставим
dear: 500
#Сколько стоит Богатое казино казино, "$" не ставим
rich: 1000
#↓Вкл/Выкл уведомления о выйграше над инвентарем
Popup: false
#↑Вкл = true Выкл = false

#↓Включить/Отключить
Auto-Update: true

#↓выбор языка доступно: 1=ru, 2=en
lang: 1
#↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
#→Все что ниже не работает ждите обновления←
#↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

#↓Что можно получить в Дешевом казино
cheapr: array(100, 200, 300, 10, 50, 250, 0)
#↓Что можно получить в Дорогом казино 
dearr: array(500,1000,100,0,300,750,50,250)
#↓Что можно получить в Богатом казино 
richr: array(500,1000,100,0,300,750,50,250,900,2000,1250,1150)
...
